In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_excel('/content/drive/MyDrive/Datasets/California(194,475) _asses - Copy.xlsx')

In [4]:
df.head()

,Email,First Name,Last Name,Suffix,Office Name,Office Address1,Office City,Office State,Office County,Office Phone,Office Fax,Cell Phone,License Type
0,kbarragan@golyon.com,Kelean,Barragan,NaN,Lyon Re Elk Grove,23488 Hacienda Dr,Acampo,CA,San Joaquin,916-683-6600,NaN,NaN,Salesperson
1,cbazett@golyon.com,Cecelia,Bazett,NaN,Lyon Re Elk Grove,23488 Hacienda Dr,Acampo,CA,San Joaquin,916-683-6600,916-683-6644,NaN,Salesperson
2,mbeecham.homes4u@gmail.com,Marylou,Beecham,NaN,Lyon Re Elk Grove,23488 Hacienda Dr,Acampo,CA,San Joaquin,916-683-6600,NaN,NaN,NaN
3,bell.samantha37@gmail.com,Samantha,Bell,NaN,White House Real Estate,3366 E Forest Lake Rd,Acampo,CA,San Joaquin,916-686-2324,866-262-3525,NaN,Salesperson
4,nbenton@golyon.com,Nancy,Benton,NaN,Lyon Re Elk Grove,23488 Hacienda Dr,Acampo,CA,San Joaquin,916-683-6600,916-683-6644,916-595-2697,Salesperson

In [5]:
df.isna().sum()

Email                   0
First Name              2
Last Name               0
Suffix             194214
Office Name           217
Office Address1         0
Office City             0
Office State            0
Office County           0
Office Phone           60
Office Fax          77063
Cell Phone         118129
License Type        21090
dtype: int64

In [6]:
df.groupby('License Type')['Email'].count().sort_values(ascending=False)

License Type
Salesperson                         127734
Broker                               45245
Associate Broke                         96
Individual Broker                       59
Sales Agent                             55
Provisional Broker                      41
Associate Broker                        26
Broker In Charge                        24
Officer                                 19
Executive Broker                        16
Sales Associate                         13
Managing Broker                         13
Broker Salesperson                       9
Principal Broker                         9
Affiliate Broker                         4
Designated Brokerr                       4
Salesperson-Standard                     3
Corporate Broker                         3
Branch Broker                            3
Reciprocal Salesperson                   2
Limited Liability Company Broker         1
Qualifying Broker                        1
Reciprocal Broker                        1
Sales                                    1
Broker Sales                             1
Broker Associate                         1
Individual Broker (Employing)            1
Name: Email, dtype: int64

In [7]:
df_filter1 = df[df['License Type'].isin(['Broker','Managing Broker',"Principal Broker"])]

In [21]:
df_filter1

,Email,First Name,Last Name,Suffix,Office Name,Office Address1,Office City,Office State,Office County,Office Phone,Office Fax,Cell Phone,License Type
5,cbird@golyon.com,Carmen,Bird,NaN,Lyon Re Elk Grove,23488 Hacienda Dr,Acampo,CA,San Joaquin,916-683-6600,916-683-6644,916-479-0414,Broker
25,charry@golyon.com,Cathy,Harry,NaN,Lyon Re Elk Grove,23488 Hacienda Dr,Acampo,CA,San Joaquin,916-683-6600,NaN,NaN,Broker
33,linda4947@att.net,Linda,Larsen Nye,NaN,Your Home Town Realty,24332 N Watkinson Rd,Acampo,CA,San Joaquin,209-365-1440,NaN,NaN,Broker
35,cathylauchland@sbcglobal.net,Cathy,Lauchland,NaN,Cathy Luchland R E Broker,6908 E Woodbridge Rd,Acampo,CA,San Joaquin,209-810-2481,209-370-8048,NaN,Broker
61,russwhite@realtor.com,Russell,White,NaN,White House Real Estate,3366 E Forest Lake Rd,Acampo,CA,San Joaquin,916-686-2324,NaN,NaN,Broker
...,...,...,...,...,...,...,...,...,...,...,...,...,...
194460,tonysalto@aol.com,Antonio,Salto,NaN,Realty 1,Po Box 417,Yucca Valley,CA,San Bernardino,760-365-9823,NaN,NaN,Broker
194465,finch636@gmail.com,Jennifer,Thacher-Finch,NaN,Thacher & Daughter Real Estate,6938 Airway,Yucca Valley,CA,San Bernardino,760-365-1100,760-365-8824,760-219-6527,Broker
194469,barti.vaidya@yahoo.com,Barti,Vaidya,NaN,Barti Vaidya Broker,8687 Grand Ave,Yucca Valley,CA,San Bernardino,760-413-8005,866-275-5728,NaN,Broker
194472,xalisrealty@hotmail.com,James,Xalis,NaN,Xalis Realty,7714 Grand Ave,Yucca Valley,CA,San Bernardino,760-365-7878,NaN,760-668-5153,Broker
194474,wardcharter@hotmail.com,Ward,Charter,NaN,Ward Charter,P O Box 457,Zamora,CA,Yolo,916-203-5454,NaN,NaN,Broker

In [22]:
df_office_county = df_filter1.groupby('Office County')['Email'].count().sort_values(ascending=False).to_frame().reset_index()

In [24]:
df_office_county.rename(columns={'Office County':'County','Email':'Count'},inplace=True)

             County  Count
0       Los Angeles  11127
1            Orange   5809
2         San Diego   4975
3         Riverside   2708
4       Santa Clara   2605
5    San Bernardino   1756
6           Alameda   1600
7      Contra Costa   1527
8        Sacramento   1392
9     San Francisco   1190
10        San Mateo   1009
11          Ventura    951
12           Placer    698
13           Fresno    673
14  San Luis Obispo    590
15           Sonoma    535
16      San Joaquin    516
17             Kern    470
18    Santa Barbara    466
19         Monterey    436
20            Marin    420
21           Solano    361
22           Nevada    352
23       Stanislaus    328
24        El Dorado    322
25       Santa Cruz    308
26            Butte    247
27           Tulare    216
28             Napa    192
29           Shasta    184
30             Yolo    125
31         Humboldt    111
32           Merced     99
33           Sutter     92
34         Tuolumne     88
35        Calaveras     85
36           Madera     81
37         Imperial     70
38            Kings     66
39        Mendocino     59
40       San Benito     56
41         Siskiyou     53
42           Amador     48
43             Lake     43
44             Mono     37
45           Tehama     32
46           Plumas     24
47             Inyo     20
48        Del Norte     19
49           Lassen     18
50             Yuba     18
51         Mariposa     17
52            Glenn     14
53          Trinity     11
54           Colusa      9
55            Modoc      7
56           Sierra      2

In [28]:
df_office_county_filter = df_office_county[(df_office_county['Count'] >= 15) & (df_office_county['Count'] <= 100)]

In [33]:
county = df_office_county_filter['County'].to_list()
county

['Merced',
 'Sutter',
 'Tuolumne',
 'Calaveras',
 'Madera',
 'Imperial',
 'Kings',
 'Mendocino',
 'San Benito',
 'Siskiyou',
 'Amador',
 'Lake',
 'Mono',
 'Tehama',
 'Plumas',
 'Inyo',
 'Del Norte',
 'Lassen',
 'Yuba',
 'Mariposa']

In [34]:
df_filter1[df_filter1['Office County'].isin(county)]

,Email,First Name,Last Name,Suffix,Office Name,Office Address1,Office City,Office State,Office County,Office Phone,Office Fax,Cell Phone,License Type
2138,diane.bateman@century21.com,Diane,Bateman,NaN,C-21 Sierra Properties Ac,Po Box 794,Altaville,CA,Calaveras,209-736-9191,209-736-6811,209-559-2711,Broker
2143,vintagenancy@att.net,Nancy,Whittle,NaN,C-21 Sierra Properties Ac,Po Box 794,Altaville,CA,Calaveras,209-736-9191,209-736-6811,209-768-9191,Broker
3341,timfland@att.net,Timothy,Folendorf,NaN,The Land Company,Po Box 2,Angels Camp,CA,Calaveras,209-736-2505,209-736-0836,209-770-4500,Broker
3347,geri@realestatesonora.com,Geri,Ramirez,NaN,Copper Creek,808 S Main St,Angels Camp,CA,Calaveras,209-984-0583,NaN,NaN,Broker
3349,dsharp.realtor@gmail.com,Don,Sharp,NaN,Don Sharp Broker,Po Box 1405,Angels Camp,CA,Calaveras,209-532-7368,NaN,NaN,Broker
...,...,...,...,...,...,...,...,...,...,...,...,...,...
194156,kal@crownecommunities.com,Kal,Takhar,NaN,Crowne Realty,319 Teegarden Ave,Yuba City,CA,Sutter,530-870-3172,NaN,NaN,Broker
194161,jptaylor6@comcast.net,John,Taylor,NaN,Coldwell Banker Commercial,781 Taber Ave,Yuba City,CA,Sutter,530-673-6614,NaN,916-826-1791,Broker
194167,mike@wmmt.com,Mike,Tomlinson,NaN,Meagher & Tomlinson,1007 Live Oak Blvd,Yuba City,CA,Sutter,530-671-0000,NaN,530-218-7499,Broker
194180,walshluk@comcast.net,Rick,Walsh,NaN,Keller Williams Realty Yuba Su,422 Century Park Dr,Yuba City,CA,Sutter,530-674-4300,530-674-7092,530-845-0083,Broker
194199,jscew@frontiernet.net,Colleen,Wrysinski,NaN,Keller Williams Realty Yuba Su,422 Century Park Dr,Yuba City,CA,Sutter,530-674-4300,NaN,530-277-7080,Broker

In [35]:
df_filter1[~df_filter1['Office County'].isin(county)]

,Email,First Name,Last Name,Suffix,Office Name,Office Address1,Office City,Office State,Office County,Office Phone,Office Fax,Cell Phone,License Type
5,cbird@golyon.com,Carmen,Bird,NaN,Lyon Re Elk Grove,23488 Hacienda Dr,Acampo,CA,San Joaquin,916-683-6600,916-683-6644,916-479-0414,Broker
25,charry@golyon.com,Cathy,Harry,NaN,Lyon Re Elk Grove,23488 Hacienda Dr,Acampo,CA,San Joaquin,916-683-6600,NaN,NaN,Broker
33,linda4947@att.net,Linda,Larsen Nye,NaN,Your Home Town Realty,24332 N Watkinson Rd,Acampo,CA,San Joaquin,209-365-1440,NaN,NaN,Broker
35,cathylauchland@sbcglobal.net,Cathy,Lauchland,NaN,Cathy Luchland R E Broker,6908 E Woodbridge Rd,Acampo,CA,San Joaquin,209-810-2481,209-370-8048,NaN,Broker
61,russwhite@realtor.com,Russell,White,NaN,White House Real Estate,3366 E Forest Lake Rd,Acampo,CA,San Joaquin,916-686-2324,NaN,NaN,Broker
...,...,...,...,...,...,...,...,...,...,...,...,...,...
194460,tonysalto@aol.com,Antonio,Salto,NaN,Realty 1,Po Box 417,Yucca Valley,CA,San Bernardino,760-365-9823,NaN,NaN,Broker
194465,finch636@gmail.com,Jennifer,Thacher-Finch,NaN,Thacher & Daughter Real Estate,6938 Airway,Yucca Valley,CA,San Bernardino,760-365-1100,760-365-8824,760-219-6527,Broker
194469,barti.vaidya@yahoo.com,Barti,Vaidya,NaN,Barti Vaidya Broker,8687 Grand Ave,Yucca Valley,CA,San Bernardino,760-413-8005,866-275-5728,NaN,Broker
194472,xalisrealty@hotmail.com,James,Xalis,NaN,Xalis Realty,7714 Grand Ave,Yucca Valley,CA,San Bernardino,760-365-7878,NaN,760-668-5153,Broker
194474,wardcharter@hotmail.com,Ward,Charter,NaN,Ward Charter,P O Box 457,Zamora,CA,Yolo,916-203-5454,NaN,NaN,Broker