In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_excel('/content/drive/MyDrive/Datasets/California(194,475) _asses - Copy.xlsx')

In [4]:
df.head()

,Email,First Name,Last Name,Suffix,Office Name,Office Address1,Office City,Office State,Office County,Office Phone,Office Fax,Cell Phone,License Type
0,kbarragan@golyon.com,Kelean,Barragan,NaN,Lyon Re Elk Grove,23488 Hacienda Dr,Acampo,CA,San Joaquin,916-683-6600,NaN,NaN,Salesperson
1,cbazett@golyon.com,Cecelia,Bazett,NaN,Lyon Re Elk Grove,23488 Hacienda Dr,Acampo,CA,San Joaquin,916-683-6600,916-683-6644,NaN,Salesperson
2,mbeecham.homes4u@gmail.com,Marylou,Beecham,NaN,Lyon Re Elk Grove,23488 Hacienda Dr,Acampo,CA,San Joaquin,916-683-6600,NaN,NaN,NaN
3,bell.samantha37@gmail.com,Samantha,Bell,NaN,White House Real Estate,3366 E Forest Lake Rd,Acampo,CA,San Joaquin,916-686-2324,866-262-3525,NaN,Salesperson
4,nbenton@golyon.com,Nancy,Benton,NaN,Lyon Re Elk Grove,23488 Hacienda Dr,Acampo,CA,San Joaquin,916-683-6600,916-683-6644,916-595-2697,Salesperson

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194475 entries, 0 to 194474
Data columns (total 13 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Email            194475 non-null  object
 1   First Name       194473 non-null  object
 2   Last Name        194475 non-null  object
 3   Suffix           261 non-null     object
 4   Office Name      194258 non-null  object
 5   Office Address1  194475 non-null  object
 6   Office City      194475 non-null  object
 7   Office State     194475 non-null  object
 8   Office County    194475 non-null  object
 9   Office Phone     194415 non-null  object
 10  Office Fax       117412 non-null  object
 11  Cell Phone       76346 non-null   object
 12  License Type     173385 non-null  object
dtypes: object(13)
memory usage: 19.3+ MB

In [7]:
df.isna().sum()

Email                   0
First Name              2
Last Name               0
Suffix             194214
Office Name           217
Office Address1         0
Office City             0
Office State            0
Office County           0
Office Phone           60
Office Fax          77063
Cell Phone         118129
License Type        21090
dtype: int64

In [8]:
df.groupby('License Type')['Email'].count().sort_values(ascending=False)

License Type
Salesperson                         127734
Broker                               45245
Associate Broke                         96
Individual Broker                       59
Sales Agent                             55
Provisional Broker                      41
Associate Broker                        26
Broker In Charge                        24
Officer                                 19
Executive Broker                        16
Sales Associate                         13
Managing Broker                         13
Broker Salesperson                       9
Principal Broker                         9
Affiliate Broker                         4
Designated Brokerr                       4
Salesperson-Standard                     3
Corporate Broker                         3
Branch Broker                            3
Reciprocal Salesperson                   2
Limited Liability Company Broker         1
Qualifying Broker                        1
Reciprocal Broker                        1
Sales                                    1
Broker Sales                             1
Broker Associate                         1
Individual Broker (Employing)            1
Name: Email, dtype: int64

In [9]:
df_filter1 = df[df['License Type'].isin(['Broker','Managing Broker',"Principal Broker"])]

In [10]:
df_filter1

,Email,First Name,Last Name,Suffix,Office Name,Office Address1,Office City,Office State,Office County,Office Phone,Office Fax,Cell Phone,License Type
5,cbird@golyon.com,Carmen,Bird,NaN,Lyon Re Elk Grove,23488 Hacienda Dr,Acampo,CA,San Joaquin,916-683-6600,916-683-6644,916-479-0414,Broker
25,charry@golyon.com,Cathy,Harry,NaN,Lyon Re Elk Grove,23488 Hacienda Dr,Acampo,CA,San Joaquin,916-683-6600,NaN,NaN,Broker
33,linda4947@att.net,Linda,Larsen Nye,NaN,Your Home Town Realty,24332 N Watkinson Rd,Acampo,CA,San Joaquin,209-365-1440,NaN,NaN,Broker
35,cathylauchland@sbcglobal.net,Cathy,Lauchland,NaN,Cathy Luchland R E Broker,6908 E Woodbridge Rd,Acampo,CA,San Joaquin,209-810-2481,209-370-8048,NaN,Broker
61,russwhite@realtor.com,Russell,White,NaN,White House Real Estate,3366 E Forest Lake Rd,Acampo,CA,San Joaquin,916-686-2324,NaN,NaN,Broker
...,...,...,...,...,...,...,...,...,...,...,...,...,...
194460,tonysalto@aol.com,Antonio,Salto,NaN,Realty 1,Po Box 417,Yucca Valley,CA,San Bernardino,760-365-9823,NaN,NaN,Broker
194465,finch636@gmail.com,Jennifer,Thacher-Finch,NaN,Thacher & Daughter Real Estate,6938 Airway,Yucca Valley,CA,San Bernardino,760-365-1100,760-365-8824,760-219-6527,Broker
194469,barti.vaidya@yahoo.com,Barti,Vaidya,NaN,Barti Vaidya Broker,8687 Grand Ave,Yucca Valley,CA,San Bernardino,760-413-8005,866-275-5728,NaN,Broker
194472,xalisrealty@hotmail.com,James,Xalis,NaN,Xalis Realty,7714 Grand Ave,Yucca Valley,CA,San Bernardino,760-365-7878,NaN,760-668-5153,Broker
194474,wardcharter@hotmail.com,Ward,Charter,NaN,Ward Charter,P O Box 457,Zamora,CA,Yolo,916-203-5454,NaN,NaN,Broker

In [11]:
df_office_county = df_filter1.groupby('Office County')['Email'].count().sort_values(ascending=False).to_frame().reset_index()

In [12]:
df_office_county.rename(columns={'Office County':'County','Email':'Count'},inplace=True)

In [13]:
df_office_county_filter = df_office_county[(df_office_county['Count'] >= 15) & (df_office_county['Count'] <= 100)]

In [14]:
county = df_office_county_filter['County'].to_list()
county

['Merced',
 'Sutter',
 'Tuolumne',
 'Calaveras',
 'Madera',
 'Imperial',
 'Kings',
 'Mendocino',
 'San Benito',
 'Siskiyou',
 'Amador',
 'Lake',
 'Mono',
 'Tehama',
 'Plumas',
 'Inyo',
 'Del Norte',
 'Lassen',
 'Yuba',
 'Mariposa']

In [15]:
df_filter2 = df_filter1[df_filter1['Office County'].isin(county)]

In [16]:
df_filter2

,Email,First Name,Last Name,Suffix,Office Name,Office Address1,Office City,Office State,Office County,Office Phone,Office Fax,Cell Phone,License Type
2138,diane.bateman@century21.com,Diane,Bateman,NaN,C-21 Sierra Properties Ac,Po Box 794,Altaville,CA,Calaveras,209-736-9191,209-736-6811,209-559-2711,Broker
2143,vintagenancy@att.net,Nancy,Whittle,NaN,C-21 Sierra Properties Ac,Po Box 794,Altaville,CA,Calaveras,209-736-9191,209-736-6811,209-768-9191,Broker
3341,timfland@att.net,Timothy,Folendorf,NaN,The Land Company,Po Box 2,Angels Camp,CA,Calaveras,209-736-2505,209-736-0836,209-770-4500,Broker
3347,geri@realestatesonora.com,Geri,Ramirez,NaN,Copper Creek,808 S Main St,Angels Camp,CA,Calaveras,209-984-0583,NaN,NaN,Broker
3349,dsharp.realtor@gmail.com,Don,Sharp,NaN,Don Sharp Broker,Po Box 1405,Angels Camp,CA,Calaveras,209-532-7368,NaN,NaN,Broker
...,...,...,...,...,...,...,...,...,...,...,...,...,...
194156,kal@crownecommunities.com,Kal,Takhar,NaN,Crowne Realty,319 Teegarden Ave,Yuba City,CA,Sutter,530-870-3172,NaN,NaN,Broker
194161,jptaylor6@comcast.net,John,Taylor,NaN,Coldwell Banker Commercial,781 Taber Ave,Yuba City,CA,Sutter,530-673-6614,NaN,916-826-1791,Broker
194167,mike@wmmt.com,Mike,Tomlinson,NaN,Meagher & Tomlinson,1007 Live Oak Blvd,Yuba City,CA,Sutter,530-671-0000,NaN,530-218-7499,Broker
194180,walshluk@comcast.net,Rick,Walsh,NaN,Keller Williams Realty Yuba Su,422 Century Park Dr,Yuba City,CA,Sutter,530-674-4300,530-674-7092,530-845-0083,Broker
194199,jscew@frontiernet.net,Colleen,Wrysinski,NaN,Keller Williams Realty Yuba Su,422 Century Park Dr,Yuba City,CA,Sutter,530-674-4300,NaN,530-277-7080,Broker

In [17]:
df_filter2.groupby('Office Name')['Email'].count().sort_values(ascending=False)

Office Name
Century 21 M&m And Associates     18
Modern Broker Inc                 13
Intero Real Estate Services       10
Century 21 Wildwood Properties    10
Century 21 Select                  9
                                  ..
Hedberg Realty                     1
Heartland Properties               1
Hadley Real Estate Services        1
Grizzly Ranch Re Services          1
Yvonne Fiorini Broker              1
Name: Email, Length: 669, dtype: int64

In [21]:
remove = [  'Zillow',
            'Better Homes and Gardens Real Estate',
            'Camden Property Trust,The Corcoran Group',
            'Sotheby’s International Realty',
            'ERA Real Estate',
            'RE/MAX',
            'Keller Williams',
            'Remax','Re max',
            'Coldwell Banker',
            'C21',
            'Centure 21',
            'Berkshire',
            'c-21'
          ]

In [22]:
df_filter3 = df_filter2[~df_filter2['Office Name'].astype(str).str.contains('|'.join(remove),case=False)]

In [23]:
df_filter3

,Email,First Name,Last Name,Suffix,Office Name,Office Address1,Office City,Office State,Office County,Office Phone,Office Fax,Cell Phone,License Type
3341,timfland@att.net,Timothy,Folendorf,NaN,The Land Company,Po Box 2,Angels Camp,CA,Calaveras,209-736-2505,209-736-0836,209-770-4500,Broker
3347,geri@realestatesonora.com,Geri,Ramirez,NaN,Copper Creek,808 S Main St,Angels Camp,CA,Calaveras,209-984-0583,NaN,NaN,Broker
3349,dsharp.realtor@gmail.com,Don,Sharp,NaN,Don Sharp Broker,Po Box 1405,Angels Camp,CA,Calaveras,209-532-7368,NaN,NaN,Broker
5665,gloria@barrywardrealty.com,Gloria,Correy,NaN,Barry Ward Realty,1122 Hwy 4,Arnold,CA,Calaveras,209-795-6600,209-795-7622,209-403-6565,Broker
5666,rolin@actionrealty.com,Rolin,Crawford,NaN,Cb Action Realty,2182 Hwy 4 C240,Arnold,CA,Calaveras,209-795-2100,209-795-0456,209-768-4260,Broker
...,...,...,...,...,...,...,...,...,...,...,...,...,...
194144,sharonstarmer@gmail.com,Sharon,Starmer,NaN,Era - Showcase Real Estate,1889 Tres Picos Dr,Yuba City,CA,Sutter,530-671-0450,NaN,NaN,Broker
194151,dstone@c21selectgroup.com,Dennis,Stone,NaN,Century 21 Select,409 Century Pk Dr Ste 1,Yuba City,CA,Sutter,530-673-7724,530-671-8189,NaN,Broker
194155,karent@wmmt.com,Karen,Tabler,NaN,Meagher & Tomlinson,1007 Live Oak Blvd,Yuba City,CA,Sutter,530-671-0000,NaN,530-713-0243,Broker
194156,kal@crownecommunities.com,Kal,Takhar,NaN,Crowne Realty,319 Teegarden Ave,Yuba City,CA,Sutter,530-870-3172,NaN,NaN,Broker
194167,mike@wmmt.com,Mike,Tomlinson,NaN,Meagher & Tomlinson,1007 Live Oak Blvd,Yuba City,CA,Sutter,530-671-0000,NaN,530-218-7499,Broker

In [24]:
df_filter3.groupby('Office Name')['Email'].count().sort_values(ascending=False)

Office Name
Century 21 M&m And Associates     18
Modern Broker Inc                 13
Century 21 Wildwood Properties    10
Intero Real Estate Services       10
Barry Ward Realty                  9
                                  ..
Hadley Real Estate Services        1
Grizzly Ranch Re Services          1
Grant Real Estate                  1
Granata Group Realty               1
Yvonne Fiorini Broker              1
Name: Email, Length: 616, dtype: int64