In [1]:
from bs4 import BeautifulSoup
from csv import writer
from urllib.request import Request, urlopen
import re

In [2]:
#extracts the max page on a search(job)
def pageFinder():
  url = f'https://www.skipthedrive.com/?s=data+analyst'
  req = Request(url, headers={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'})
  webpage = urlopen(req).read()
  soup = BeautifulSoup(webpage, 'html.parser')
  a_href =soup.find("a",{"class":"number lastp"}).get("href")
  maxPage = re.findall(r'\d+', a_href)

  return int(maxPage[0])

In [3]:
import pandas as pd

In [4]:
def scrapedJobs():
  search = 'data+analyst'
  jobposted = {'Jobtitle':[],'Company':[],'Date_posted':[], 'URL':[]}

  for i in range(0,pageFinder()+1):
    url = f'https://www.skipthedrive.com/page/{i}/?s={search}'
    req = Request(url, headers={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'})
    webpage = urlopen(req).read()
    soup = BeautifulSoup(webpage, 'html.parser')

    jobtitle = soup.find_all('h2', class_='post-title entry-title')
    soup.find('span', class_="custom_fields_company_name_display_search_results main_content_padding").decompose()
    companyname = soup.find_all('span', class_="custom_fields_company_name_display_search_results")
    date = soup.find_all('span', class_='custom_fields_job_date_display_search_results')
    href=soup.find_all('h2', class_='post-title entry-title')



    for i in range(0,len(jobtitle)):

      jobposted['Jobtitle'].append(jobtitle[i].text)
      jobposted['Company'].append(companyname[i].text)
      jobposted['Date_posted'].append(date[i].text)
      jobposted['URL'].append(href[i].a['href'])

  

  return jobposted

In [5]:
data = pd.DataFrame(scrapedJobs())
data

,Jobtitle,Company,Date_posted,URL
0,Information Security Analyst,\n Rethink First,"\n November 5, 2022",https://www.skipthedrive.com/job/rethink-first...
1,"Senior Data Engineer (Remote, Canada)",\n OpenTable,"\n November 4, 2022",https://www.skipthedrive.com/job/opentable-sen...
2,Technical Business Analyst,\n Narvar,"\n November 4, 2022",https://www.skipthedrive.com/job/narvar-techni...
3,"Senior Systems Analyst, FP&A",\n Dropbox,"\n November 4, 2022",https://www.skipthedrive.com/job/dropbox-senio...
4,"Senior Data Engineer (Remote, Mexico)",\n OpenTable,"\n November 4, 2022",https://www.skipthedrive.com/job/opentable-sen...
...,...,...,...,...
935,"Business Systems Analyst, Financial Retail App...",\n Specialized,"\n September 6, 2022",https://www.skipthedrive.com/job/specialized-b...
936,Business Systems Analyst – Salesforce,\n Specialized,"\n September 6, 2022",https://www.skipthedrive.com/job/specialized-b...
937,Senior Data Scientist (Remote Friendly),\n Mission Lane,"\n September 6, 2022",https://www.skipthedrive.com/job/mission-lane-...
938,"Counsel – Privacy, Data, and Technology",\n Specialized,"\n September 6, 2022",https://www.skipthedrive.com/job/specialized-c...
939,Sr. Business Analyst – Finance,\n Specialized,"\n September 6, 2022",https://www.skipthedrive.com/job/specialized-s...

In [6]:
data.to_csv('jobslisting.csv')